def options(opt):
    opt.load('compiler_c')  # Загружаем поддержку C-компилятора

def configure(conf):
    conf.find_program('arm-none-eabi-gcc', var='CC')
    conf.find_program('arm-none-eabi-gcc', var='LINK_CC')  # Для компоновки

def build(bld):
    # Указываем исходные файлы и цель
    bld(
        features='c cprogram',  # Компиляция программы на C
        source='main.c',        # Ваш исходный файл(ы)
        target='app.elf'        # Имя выходного файла
    )